### ISSUE TITLE
Invalid format style code for "time" data type

### ISSUE THREAD

**Issue by aroder** [s7clarke10/tap-sybase#27]
**Summary**

The format style code 140 is for datetime data type but is not for time data type

**Details**
The code at 
https://github.com/s7clarke10/tap-sybase/blob/c71c20c91ab08aa87e86ef927afeea8331cbe6f7/tap_sybase/sync_strategies/common.py#L118-L119 checks for the "time" data type, and attempts to convert it to character using format style code 140.

However, 140 is valid only for datetime, not for time
![image](https://github.com/user-attachments/assets/0f92069d-8e79-4a98-85fb-8cb56f383271)

reference Sybase docs: https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1604/doc/html/san1278453000116.html

This is reproducible directly in Sybase
![image](https://github.com/user-attachments/assets/84c222ce-9f0a-496f-bc4d-a98a263b40a4)

Code 108 works just fine though
![image](https://github.com/user-attachments/assets/14d025cd-aa1d-4c1e-991d-97fb03edc551)

**Comment by aroder** [comment]
this seems to work and be compatible with the "time(9)" data type that target-snowflake and I assume others will generate in the target table

LTRIM(RTRIM(CONVERT(CHAR, {}, 108)))

**Comment by s7clarke10** [comment]
Thanks for raising this issue, I am busy with another assignment and have limited access to Sybase at the moment. I will raise this with a colleague of mine who I collaborate with on these enhancements.

**Comment by s7clarke10** [comment]
It is worth mentioning that I have been working with a couple of different styles of Sybase and the particular version we were using is rather old. I had a great deal of difficulty finding codes which are suitable for old versions of Sybase.

**Comment by mjsqu** [comment]
I have checked our flavours of Sybase and we do not even have the time type (not present in the `dbo.systypes` system object), so this change would not impact us at all as no columns will ever come through with this type.
